### PR TITLE
108 reestablish connection to voucher execution listener

### PR DESCRIPTION
**Pull request by sandhilt**

### CODE REVIEW

**Review by fabiooshiro — CHANGES_REQUESTED** [review]
You may need to add a time.Sleep in that part too

```bash
20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
[20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
[20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
[20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
[20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
[20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
[20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
[20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
[20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
[20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
[20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
[20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
[20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
[20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
[20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
[20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
[20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
[20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
[20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
[20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
[20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
[20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
[20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
[20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
[20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
[20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
[20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
[20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
[20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
[20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
[20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
[20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
[20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
[20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
[20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
[20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
```

**Comment by fabiooshiro** [comment]
To test the scenario:
1. open one terminal and run anvil 
2. open another terminal and run nonodo using the flag --disable-devnet
3. then, stop anvil on the first terminal.

Spoiler:
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

**Run the postgraphile**

```bash
docker network create mynetwork
docker build -t postgresteste:latest ./postgres
docker run -d --network mynetwork -p 5432:5432 --name postgres postgresteste:latest

docker build -t postgraphile-custom ./postgraphile/
docker run -d --network mynetwork -p 5000:5000 --name postgraphile-custom postgraphile-custom
```

**Run nonodo with --disable-devnet**

```bash
export POSTGRES_HOST=127.0.0.1
export POSTGRES_PORT=5432
export POSTGRES_DB=mydatabase
export POSTGRES_USER=myuser
export POSTGRES_PASSWORD=mypassword
./nonodo --http-address=0.0.0.0 --high-level-graphql --enable-debug --node-version v2 --db-implementation postgres --disable-devnet
```

**Comment by sandhilt** [comment]
> You may need to add a time.Sleep in that part too
> 
> ```shell
> 20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
> [20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
> [20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
> [20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
> [20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
> [20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
> [20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
> [20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
> [20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
> [20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
> [20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
> [20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
> [20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
> [20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
> [20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
> [20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
> [20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
> [20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
> [20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
> [20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
> [20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
> [20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
> [20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
> [20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
> [20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
> [20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
> [20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
> [20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
> [20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
> [20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
> [20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
> [20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
> [20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
> [20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
> [20:46:57.106] ERR convenience/voucher_exec_listener.go:149 unexpected readPastExecutions error error="dial tcp 127.0.0.1:8545: connect: connection refused"
> [20:46:57.106] DBG convenience/voucher_exec_listener.go:106 ReadPastExecutions FromBlock=0
> ```

In this case, Graphille doesn't run, and Nonodo exits with an error after a timeout of a few seconds, just like any other worker.

Nonodo timeout

Code timeout:
https://github.com/Calindra/nonodo/blob/25dcd62e35d70fe7d89f10322c620bbf23b41667/internal/supervisor/supervisor.go#L61

Broke graphile:
Log docker from graphile

**Comment by sandhilt** [comment]
> To test the scenario:
> 
>     1. open one terminal and run anvil
> 
>     2. open another terminal and run nonodo using the flag --disable-devnet
> 
>     3. then, stop anvil on the first terminal.
> 
> 
> Spoiler: . . . . . . . . . . . . . . . .
> 
> **Run the postgraphile**
> 
> ```shell
> docker network create mynetwork
> docker build -t postgresteste:latest ./postgres
> docker run -d --network mynetwork -p 5432:5432 --name postgres postgresteste:latest
> 
> docker build -t postgraphile-custom ./postgraphile/
> docker run -d --network mynetwork -p 5000:5000 --name postgraphile-custom postgraphile-custom
> ```
> 
> **Run nonodo with --disable-devnet**
> 
> ```shell
> export POSTGRES_HOST=127.0.0.1
> export POSTGRES_PORT=5432
> export POSTGRES_DB=mydatabase
> export POSTGRES_USER=myuser
> export POSTGRES_PASSWORD=mypassword
> ./nonodo --http-address=0.0.0.0 --high-level-graphql --enable-debug --node-version v2 --db-implementation postgres --disable-devnet
> ```

@fabiooshiro try run:

```shell
go run . --http-address=0.0.0.0 --high-level-graphql --enable-debug --node-version v2 --db-implementation postgres --disable-devnet
```

**Review by fabiooshiro — APPROVED** [review]
LGTM!!!

**Pull request merged**
