### PR TITLE
Refactor inputBoxIndex to int64

### PR DESCRIPTION
**Pull request by sandhilt**
This pull request refactors the `inputBoxIndex` field from `int` to `int64` in multiple files. The changes ensure consistency and compatibility with the data type used in other parts of the codebase from ABI contract.

### CODE REVIEW

**Review by ZzzzHui — APPROVED** [review]
Nice

**Comment by sandhilt** [comment]
@fabiooshiro keep `int64` or change for `string`?

**Comment by ZzzzHui** [comment]
@sandhilt Was this branch merged?

**Comment by sandhilt** [comment]
> @sandhilt Was this branch merged?

Hi! No, I won't merge this. Are you still having issues with that?

**Comment by ZzzzHui** [comment]
Hey @sandhilt . No issues. I can apply the fix in my own branch. Just double checking with you :) Thanks

**Pull request closed without merging**
